import json
import os
import requests
import subprocess  # Naya module commands ko automatically run karne ke liye

# Fetch Gemini API key from GitHub Secrets
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")

def read_trivy_report():
    try:
        # Open and load the JSON report generated by Trivy
        with open('trivy-results.json', 'r') as file:
            report = json.load(file)
            return report
    except FileNotFoundError:
        print("No Trivy report found. Everything looks secure!")
        return None

def ask_gemini_for_fix(report):
    print("Sending vulnerability data to Gemini AI...")
    
    # Truncate the report to prevent exceeding API token limits
    bug_details = str(report)[:1500] 
    
    # STRICT PROMPT: Sirf raw commands maang rahe hain bina kisi markdown ke
    prompt = f"""You are a DevSecOps Expert. Read this Trivy vulnerability report.
Your ONLY job is to provide the exact terminal commands (like npm install package@version) needed to fix these vulnerabilities.
RULES:
1. ONLY output raw commands.
2. NO markdown formatting, NO backticks (```), NO explanations.
3. Put each command on a new line.

Report:
{bug_details}"""

    # Define the Gemini API endpoint
    url = f"[https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=](https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=){GEMINI_API_KEY}"
    
    headers = {
        "Content-Type": "application/json"
    }
    
    data = {
        "contents": [{"parts": [{"text": prompt}]}]
    }

    # Send POST request to the Gemini API
    response = requests.post(url, headers=headers, json=data)
    
    if response.status_code == 200:
        result = response.json()
        return result['candidates'][0]['content']['parts'][0]['text']
    else:
        print("Gemini API Error:", response.text)
        return None

def apply_ai_fix(commands_text):
    if not commands_text:
        return
        
    print("\n--- APPLYING AI FIXES AUTOMATICALLY ---\n")
    # AI ke answer ko lines mein todna taaki ek-ek karke run kar sakein
    commands = commands_text.strip().split('\n')
    
    for cmd in commands:
        cmd = cmd.strip()
        if cmd:  # Agar line khali nahi hai
            print(f"Running Command: {cmd}")
            try:
                # Command ko terminal mein execute karna
                subprocess.run(cmd, shell=True, check=True)
                print("✅ Success!")
            except subprocess.CalledProcessError as e:
                print(f"❌ Failed to execute. Error: {e}")

if __name__ == "__main__":
    # Execute the workflow
    trivy_data = read_trivy_report()
    if trivy_data:
        ai_solution = ask_gemini_for_fix(trivy_data)
        
        print("\n--- GEMINI AI SUGGESTED COMMANDS ---\n")
        print(ai_solution)
        
        # Naya function call jo fix ko automatically apply karega
        apply_ai_fix(ai_solution)