name: PixelCraft AI DevSecOps Pipeline

# Pipeline kab chalegi? Jab bhi koi 'main' branch par code push karega
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-gates:
    name: Automated Security Scans
    runs-on: ubuntu-latest

    steps:
      # Step 1: Tumhara code GitHub server par clone hoga
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Gate 1 - Secret Scanning (TruffleHog)
      # Ye check karega ki galti se koi AWS Key ya password to code me nahi hai
      - name: Run TruffleHog Secret Scanner
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

      # Step 3: Gate 2 - SCA / Dependency Scan (Snyk)
      # Ye check karega ki kisi package me koi vulnerability to nahi hai
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --severity-threshold=high # Sirf High/Critical bugs par fail karega okay